/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControleProduto;
import controle.ModeloTabela;
import controle.Utilitarios;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloProduto;

/**
 *
 * @author jmtis
 */
public class CadastroProduto extends javax.swing.JFrame {

    ConectaBanco ConnProduto = new ConectaBanco();
    ConectaBanco connPesquisa = new ConectaBanco();
    ModeloProduto mod = new ModeloProduto();
    ControleProduto control = new ControleProduto();
    Utilitarios util = new Utilitarios();
    int flag = 1;

    public CadastroProduto() {
        initComponents();
        preencheCombo();
        util.Icone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblPrecoCompra = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        txtPrecodeCompra = new javax.swing.JTextField();
        lblPrecodeVenda = new javax.swing.JLabel();
        txtPrecodeVenda = new javax.swing.JTextField();
        lblFornecedor = new javax.swing.JLabel();
        cbxFornecedor = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoduto = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCadastraFornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCodigo.setText("Código:");

        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.setEnabled(false);

        lblDescricao.setText("Descrição:");

        txtDescricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescricao.setEnabled(false);

        lblPrecoCompra.setText("Preço de Compra:");

        lblQuantidade.setText("Quantidade:");

        txtQuantidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtQuantidade.setEnabled(false);
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        txtPrecodeCompra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecodeCompra.setEnabled(false);

        lblPrecodeVenda.setText("Preço de Venda:");

        txtPrecodeVenda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecodeVenda.setEnabled(false);

        lblFornecedor.setText("Fornecedor:");

        cbxFornecedor.setEnabled(false);

        tblPoduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPoduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPodutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPoduto);

        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCadastraFornecedor.setText("Cadastrar Fornecedor");
        btnCadastraFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFornecedor)
                            .addComponent(lblCodigo)
                            .addComponent(lblQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDescricao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDescricao))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblPrecoCompra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPrecodeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPrecodeVenda)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtPrecodeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addComponent(btnCadastraFornecedor))))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecoCompra)
                    .addComponent(txtPrecodeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecodeVenda)
                    .addComponent(txtPrecodeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedor)
                    .addComponent(cbxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastraFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnPesquisa.setEnabled(true);
        txtDescricao.setEnabled(!true);
        txtPrecodeCompra.setEnabled(!true);
        txtPrecodeVenda.setEnabled(!true);
        txtQuantidade.setEnabled(!true);
        cbxFornecedor.setEnabled(!true);
        if (flag == 1) {
            mod.setFornecedor((String) cbxFornecedor.getSelectedItem());
            mod.setProduto(txtDescricao.getText());
            mod.setPrecoCompra(Float.parseFloat(txtPrecodeCompra.getText()));
            mod.setPrecoVenda(Float.parseFloat(txtPrecodeVenda.getText()));
            mod.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            control.Salvar(mod);
        } else {
            mod.setId(Integer.parseInt(txtCodigo.getText()));
            mod.setProduto(txtDescricao.getText());
            mod.setPrecoCompra(Float.parseFloat(txtPrecodeCompra.getText()));
            mod.setFornecedor((String) cbxFornecedor.getSelectedItem());
            mod.setPrecoVenda(Float.parseFloat(txtPrecodeVenda.getText()));
            mod.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            control.Editar(mod);

        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastraFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraFornecedorActionPerformed
        CadastroFornecedor fornecedor = new CadastroFornecedor();
        fornecedor.setVisible(true);
        preencheCombo();
    }//GEN-LAST:event_btnCadastraFornecedorActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        
        preencherTabela("select * from produto where nome_produto like '%" + txtPesquisa.getText() + "%'");
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        flag = 2;
        txtDescricao.setEnabled(true);
        txtPrecodeCompra.setEnabled(true);
        txtPrecodeVenda.setEnabled(true);
        txtQuantidade.setEnabled(true);
        cbxFornecedor.setEnabled(true);
        btnSalvar.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        mod.setId(Integer.parseInt(txtCodigo.getText()));
        control.Excluir(mod);
        txtCodigo.setText("");
        txtDescricao.setText("");
        txtPesquisa.setText("");
        txtPrecodeCompra.setText("");
        txtPrecodeVenda.setText("");
        txtQuantidade.setText("");
        cbxFornecedor.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(!true);
        btnExcluir.setEnabled(!true);
        btnPesquisa.setEnabled(true);

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtDescricao.setEnabled(true);
        txtPrecodeCompra.setEnabled(true);
        txtPrecodeVenda.setEnabled(true);
        txtQuantidade.setEnabled(true);
        cbxFornecedor.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        txtPesquisa.setEnabled(false);
        btnPesquisa.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void tblPodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPodutoMouseClicked
        String descricao_produto = "" + tblPoduto.getValueAt(tblPoduto.getSelectedRow(), 0);
        ConnProduto.conexao();
        connPesquisa.conexao();

        try {
            ConnProduto.executaSQL("select * from produto where nome_produto = '" + descricao_produto + "'");
            ConnProduto.rs.first();
            txtCodigo.setText(String.valueOf(ConnProduto.rs.getInt("id_produto")));
            txtDescricao.setText(ConnProduto.rs.getString("nome_produto"));
            txtPrecodeCompra.setText(String.valueOf(ConnProduto.rs.getFloat("preco_compra")));
            txtPrecodeVenda.setText(String.valueOf(ConnProduto.rs.getFloat("preco_venda")));
            txtQuantidade.setText(String.valueOf(ConnProduto.rs.getInt("quantidade")));
            connPesquisa.executaSQL("select * from fornecedores where id_fornecedor = " + ConnProduto.rs.getInt("id_fornecedor"));
            connPesquisa.rs.first();
            cbxFornecedor.setSelectedItem(connPesquisa.rs.getString("nome_fornecedor"));
            ConnProduto.desconecta();
            connPesquisa.desconecta();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Buscar Registros \n ERRO:  " + ex);
        }
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_tblPodutoMouseClicked

    public void preencheCombo() {
        ConnProduto.conexao();

        try {
            ConnProduto.executaSQL("select * from fornecedores order by nome_fornecedor");
            ConnProduto.rs.first();
            cbxFornecedor.removeAllItems();
            do {
                cbxFornecedor.addItem(ConnProduto.rs.getString("nome_fornecedor"));
            } while (ConnProduto.rs.next());
            ConnProduto.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher Lista de Fornecedores!! \n ERRO:  " + ex);
            ConnProduto.desconecta();
        }
    }

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"DESCRIÇÃO", "QUANTIDADE", "PREÇO DE VENDA"};
        ConnProduto.conexao();

        ConnProduto.executaSQL(sql);
        try {
            ConnProduto.rs.first();
            do {
                dados.add(new Object[]{ConnProduto.rs.getString("nome_produto"), ConnProduto.rs.getInt("quantidade"), ConnProduto.rs.getFloat("preco_venda")});
            } while (ConnProduto.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não Contem Produto Cadastrado no Banco de Dados  !");
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tblPoduto.setModel(modelo);
        tblPoduto.getColumnModel().getColumn(0).setPreferredWidth(233);
        tblPoduto.getColumnModel().getColumn(0).setResizable(false);
        tblPoduto.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblPoduto.getColumnModel().getColumn(1).setResizable(false);
        tblPoduto.getColumnModel().getColumn(2).setPreferredWidth(233);
        tblPoduto.getColumnModel().getColumn(2).setResizable(false);
        tblPoduto.getTableHeader().setResizingAllowed(false);
        tblPoduto.setAutoResizeMode(tblPoduto.AUTO_RESIZE_OFF);
        tblPoduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastraFornecedor;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbxFornecedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblPrecoCompra;
    private javax.swing.JLabel lblPrecodeVenda;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTable tblPoduto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPrecodeCompra;
    private javax.swing.JTextField txtPrecodeVenda;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
