/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControleCheque;
import controle.ModeloTabela;
import controle.Utilitarios;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloCheque;

/**
 *
 * @author luizf
 */
public class CadastroCheque extends javax.swing.JFrame {

    Utilitarios util = new Utilitarios();
    ConectaBanco connCheque = new ConectaBanco();
    ModeloCheque mod = new ModeloCheque();
    ControleCheque control = new ControleCheque();
    int flag = 1;

    public CadastroCheque() {
        initComponents();
        util.Icone(this);
        util.carregaDataAtual(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        bntSair = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNumeroCheque = new javax.swing.JLabel();
        txtNumeroCheque = new javax.swing.JTextField();
        lblEmissao = new javax.swing.JLabel();
        txtfEmissao = new javax.swing.JFormattedTextField();
        lblVencimento = new javax.swing.JLabel();
        txtfVencimento = new javax.swing.JFormattedTextField();
        lblCliente = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnBuscaCliente = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        lblContaCheque = new javax.swing.JLabel();
        txtContaCheque = new javax.swing.JTextField();
        lblAgecia = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        lblBanco = new javax.swing.JLabel();
        txtBanco = new javax.swing.JTextField();
        lblTitularCheque = new javax.swing.JLabel();
        txtTitularCheque = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        lblObservacao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCheque = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        cbxStatus = new javax.swing.JComboBox<>();
        lblCodigo = new javax.swing.JLabel();
        txtCodigoCheque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cheque");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNovo.setText("novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        bntSair.setText("Sair");
        bntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntSair))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNovo)
                .addComponent(btnEditar)
                .addComponent(btnSalvar)
                .addComponent(btnExcluir)
                .addComponent(bntSair))
        );

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNumeroCheque.setText("Num.do Cheque:");

        txtNumeroCheque.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNumeroCheque.setEnabled(false);

        lblEmissao.setText("Emissão:");

        txtfEmissao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfEmissao.setEnabled(false);

        lblVencimento.setText("Vencimento:");

        txtfVencimento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfVencimento.setEnabled(false);

        lblCliente.setText("Cliente:");

        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.setEnabled(false);

        btnBuscaCliente.setText("Busca");
        btnBuscaCliente.setEnabled(false);
        btnBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaClienteActionPerformed(evt);
            }
        });

        txtCliente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCliente.setEnabled(false);

        lblContaCheque.setText("Conta do CHQ:");

        txtContaCheque.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtContaCheque.setEnabled(false);

        lblAgecia.setText("Agencia do CHQ:");

        txtAgencia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAgencia.setEnabled(false);

        lblBanco.setText("Banco do CHQ:");

        txtBanco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtBanco.setEnabled(false);

        lblTitularCheque.setText("Titular do Cheque:");

        txtTitularCheque.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTitularCheque.setEnabled(false);

        lblValor.setText("Valor R$:");

        txtValor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValor.setEnabled(false);

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        txtObservacao.setEnabled(false);
        jScrollPane1.setViewportView(txtObservacao);

        lblObservacao.setText("Observações");

        tblCheque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCheque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChequeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCheque);

        lblStatus.setText("Status:");

        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CADASTRADO", "DEPOSITADO", "COMPENSADO", "DEVOLVIDO 11", "DEVOLVIDO 12", "CONCILIAÇÃO DE CHEQUES", "CANCELA DEVOLUÇÃO", "CANCELA CONPENSAÇÃO", "CANCELA DEPOSITO", "PASSADO A TERCEIROS" }));
        cbxStatus.setEnabled(false);

        lblCodigo.setText("Código:");

        txtCodigoCheque.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoCheque.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblValor)
                            .addComponent(lblTitularCheque)
                            .addComponent(lblContaCheque)
                            .addComponent(lblCliente)
                            .addComponent(lblObservacao)
                            .addComponent(lblCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblVencimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtTitularCheque)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCodigoCheque, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContaCheque, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblAgecia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblBanco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBanco))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btnBuscaCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCliente))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblNumeroCheque)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEmissao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroCheque)
                        .addComponent(txtNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmissao)
                        .addComponent(txtfEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(txtCodigoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCliente)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblContaCheque)
                        .addComponent(txtContaCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAgecia))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBanco)
                        .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitularCheque)
                    .addComponent(txtTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus)
                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVencimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisa)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        preencherTabela("SELECT * FROM CHEQUE INNER JOIN CLIENTES ON CLIENTES.ID_CLIENTE=CHEQUE.ID_CLIENTE"
                + " WHERE CLIENTES.NOME_CLIENTE LIKE '%" + txtPesquisa.getText() + "%'");
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void bntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSairActionPerformed
        dispose();
    }//GEN-LAST:event_bntSairActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        util.limparTodosCampos(this);
        util.carregaDataAtual(this);
        util.habilitaCampos(this);
        txtfEmissao.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnBuscaCliente.setEnabled(true);
        txtCodigoCheque.setEnabled(false);

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaClienteActionPerformed
        connCheque.conexao();

        try {
            connCheque.executaSQL("SELECT * FROM CLIENTES WHERE NOME_CLIENTE LIKE '%" + txtCodigo.getText() + "%'");
            connCheque.rs.first();
            txtCliente.setText(connCheque.rs.getString("nome_cliente"));
            txtCodigo.setText(connCheque.rs.getString("cpf_cliente"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum Registro Encontrado!\n" + ex);
        }
        connCheque.desconecta();
    }//GEN-LAST:event_btnBuscaClienteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (flag == 1) {
            mod.setAgenciaCheque(txtAgencia.getText());
            mod.setBancoCheque(txtBanco.getText());
            mod.setContaCheque(txtContaCheque.getText());
            mod.setEmissaoCheque(txtfEmissao.getText());
            mod.setIdCliente(txtCodigo.getText());
            mod.setNomeTerceiro(txtTitularCheque.getText());
            mod.setNumeroCheque(Integer.parseInt(txtNumeroCheque.getText()));
            mod.setObservacaoCheuque(txtObservacao.getText());
            mod.setStatusCheque((String) cbxStatus.getSelectedItem());
            mod.setValorCheque(Double.parseDouble(txtValor.getText()));
            mod.setVencimentoCheque(txtfVencimento.getText());
            control.inserir(mod);
        } else {
            mod.setIdCheque(Integer.parseInt(txtCodigoCheque.getText()));
            mod.setAgenciaCheque(txtAgencia.getText());
            mod.setBancoCheque(txtBanco.getText());
            mod.setContaCheque(txtContaCheque.getText());
            mod.setEmissaoCheque(txtfEmissao.getText());
            mod.setIdCliente(txtCodigo.getText());
            mod.setNomeTerceiro(txtTitularCheque.getText());
            mod.setNumeroCheque(Integer.parseInt(txtNumeroCheque.getText()));
            mod.setObservacaoCheuque(txtObservacao.getText());
            mod.setStatusCheque((String) cbxStatus.getSelectedItem());
            mod.setValorCheque(Double.parseDouble(txtValor.getText()));
            mod.setVencimentoCheque(txtfVencimento.getText());
            control.alterar(mod);
        }
        btnExcluir.setEnabled(true);
        util.desabilitaCampos(this);
        txtPesquisa.setEnabled(true);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        mod.setIdCheque(Integer.parseInt(txtCodigoCheque.getText()));
        control.excluirCheque(mod);
        util.limparTodosCampos(this);
        util.desabilitaCampos(this);
        txtPesquisa.setEnabled(true);

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblChequeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChequeMouseClicked
        String numeroCheque = "" + tblCheque.getValueAt(tblCheque.getSelectedRow(), 0);
        connCheque.conexao();

        try {
            connCheque.executaSQL("SELECT * FROM CHEQUE INNER JOIN CLIENTES ON CHEQUE.ID_CLIENTE=CLIENTES.ID_CLIENTE"
                    + " WHERE CHEQUE.NUMERO_CHEQUE = '" + numeroCheque + "'");
            connCheque.rs.first();
            txtCodigoCheque.setText(String.valueOf(connCheque.rs.getInt("id_cheque")));
            txtNumeroCheque.setText(String.valueOf(connCheque.rs.getInt("numero_cheque")));
            txtfEmissao.setText(connCheque.rs.getString("emissao"));
            txtAgencia.setText(connCheque.rs.getString("agencia_cheque"));
            txtBanco.setText(connCheque.rs.getString("banco_cheque"));
            txtCliente.setText(connCheque.rs.getString("nome_cliente"));
            txtCodigo.setText(connCheque.rs.getString("cpf_cliente"));
            txtContaCheque.setText(connCheque.rs.getString("conta_cheque"));
            txtObservacao.setText(connCheque.rs.getString("observacoes_cheque"));
            txtTitularCheque.setText(connCheque.rs.getString("nome_terceiro"));
            txtValor.setText(String.valueOf(connCheque.rs.getFloat("valor_cheque")));
            txtfVencimento.setText(connCheque.rs.getString("vencimento_cheque"));
            cbxStatus.setSelectedItem((String) connCheque.rs.getString("status_cheque"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não Foi Possivel Carregar o Registro!!\n" + ex);
        }
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnNovo.setEnabled(true);
        connCheque.desconecta();
    }//GEN-LAST:event_tblChequeMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      flag = 2;
      util.habilitaCampos(this);
      btnSalvar.setEnabled(true);
      txtCodigoCheque.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"N° CHEQUE", "EMISSÃO", "VENCIMENTO", "STATUS"};
        connCheque.conexao();

        connCheque.executaSQL(sql);
        try {
            connCheque.rs.first();
            do {
                dados.add(new Object[]{connCheque.rs.getString("numero_cheque"), connCheque.rs.getString("emissao"), connCheque.rs.getString("vencimento_cheque"), connCheque.rs.getString("status_cheque")});
            } while (connCheque.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não Contem Cheque Cadastrado no Banco de Dados  !");
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tblCheque.setModel(modelo);
        tblCheque.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblCheque.getColumnModel().getColumn(0).setResizable(false);
        tblCheque.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblCheque.getColumnModel().getColumn(1).setResizable(false);
        tblCheque.getColumnModel().getColumn(2).setPreferredWidth(115);
        tblCheque.getColumnModel().getColumn(2).setResizable(false);
        tblCheque.getColumnModel().getColumn(3).setPreferredWidth(233);
        tblCheque.getColumnModel().getColumn(3).setResizable(false);
        tblCheque.getTableHeader().setResizingAllowed(false);
        tblCheque.setAutoResizeMode(tblCheque.AUTO_RESIZE_OFF);
        tblCheque.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCheque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSair;
    private javax.swing.JButton btnBuscaCliente;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgecia;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContaCheque;
    private javax.swing.JLabel lblEmissao;
    private javax.swing.JLabel lblNumeroCheque;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitularCheque;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVencimento;
    private javax.swing.JTable tblCheque;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCheque;
    private javax.swing.JTextField txtContaCheque;
    private javax.swing.JTextField txtNumeroCheque;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtTitularCheque;
    private javax.swing.JTextField txtValor;
    private javax.swing.JFormattedTextField txtfEmissao;
    private javax.swing.JFormattedTextField txtfVencimento;
    // End of variables declaration//GEN-END:variables
}
