/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConectaBanco;
import controle.ControleCliente;
import controle.ModeloTabela;
import controle.Utilitarios;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelo.ModeloCliente;

public class CadastroCliente extends javax.swing.JFrame {

    ModeloCliente mod = new ModeloCliente();
    ConectaBanco ConnCliente = new ConectaBanco();
    ControleCliente control = new ControleCliente();
    int flag = 1;
    ConectaBanco conn = new ConectaBanco();
    ConectaBanco connCidade = new ConectaBanco();
    ConectaBanco connEstado = new ConectaBanco();
    Utilitarios util = new Utilitarios();

    public CadastroCliente() {
        initComponents();
        CarregaEstado();
        util.Icone(this);

        try {
            MaskFormatter form = new MaskFormatter("##.###.###-#");
            txtfRg.setFormatterFactory(new DefaultFormatterFactory(form));
            form = new MaskFormatter("###.###.###-##");
            txtfCpf.setFormatterFactory(new DefaultFormatterFactory(form));
            form = new MaskFormatter("(##)####-####");
            txtfTelefone.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro na Formatação dos Campos !!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtfCpf = new javax.swing.JFormattedTextField();
        txtfRg = new javax.swing.JFormattedTextField();
        btnSair = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEcluir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        cbxCidade = new javax.swing.JComboBox();
        txtBairro = new javax.swing.JTextField();
        txtfTelefone = new javax.swing.JFormattedTextField();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox();
        btnListarCidade = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCodigo.setText("Código:");

        lblNome.setText("Nome:");

        lblEndereco.setText("Endereço:");

        lblCpf.setText("CPF:");

        lblRg.setText("RG:");

        lblTelefone.setText("Telefone:");

        lblBairro.setText("Bairro:");

        lblCidade.setText("Cidade:");

        txtCodigo.setEnabled(false);

        txtNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNome.setEnabled(false);

        txtEndereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEndereco.setEnabled(false);

        txtfCpf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfCpf.setEnabled(false);

        txtfRg.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfRg.setEnabled(false);

        btnSair.setText("sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEcluir.setText("Excluir");
        btnEcluir.setEnabled(false);
        btnEcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcluirActionPerformed(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCliente);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        cbxCidade.setEnabled(false);

        txtBairro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtBairro.setEnabled(false);

        txtfTelefone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfTelefone.setEnabled(false);

        lblEstado.setText("Estado:");

        cbxEstado.setEnabled(false);

        btnListarCidade.setText("Listar Cidades");
        btnListarCidade.setEnabled(false);
        btnListarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEndereco)
                            .addComponent(lblCodigo)
                            .addComponent(lblCpf)
                            .addComponent(lblEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTelefone)
                                .addGap(257, 257, 257))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(342, 342, 342)
                                        .addComponent(btnPesquisar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSair))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnListarCidade)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(146, 146, 146))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRg)
                    .addComponent(txtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf)
                    .addComponent(lblTelefone)
                    .addComponent(txtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarCidade))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnEcluir)
                    .addComponent(btnSair)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(636, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtEndereco.setEnabled(true);
        txtNome.setEnabled(true);
        txtfCpf.setEnabled(true);
        txtfRg.setEnabled(true);
        txtBairro.setEnabled(true);
        txtfTelefone.setEnabled(true);
        txtBairro.setText("");
        txtfTelefone.setText("");
        txtCodigo.setText("");
        txtEndereco.setText("");
        txtNome.setText("");
        txtfRg.setText("");
        txtfCpf.setText("");
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnPesquisar.setEnabled(false);
        txtPesquisa.setEnabled(false);
        cbxCidade.setEnabled(true);
        cbxEstado.setEnabled(true);
        btnListarCidade.setEnabled(true);
        CarregaEstado();

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (flag == 1) {
            mod.setNome(txtNome.getText());
            mod.setEndereco(txtEndereco.getText());
            mod.setCpf(txtfCpf.getText().replace("/.-", ""));
            mod.setRg(txtfRg.getText());
            mod.setBairro(txtBairro.getText());
            mod.setTelefone(txtfTelefone.getText());
            mod.setEstado((String) cbxEstado.getSelectedItem());
            mod.setCidade((String) cbxCidade.getSelectedItem());
            control.SalvarCliente(mod);
            txtEndereco.setEnabled(!true);
            txtNome.setEnabled(!true);
            txtfCpf.setEnabled(!true);
            txtfRg.setEnabled(!true);
            txtBairro.setEnabled(false);
            txtfTelefone.setEnabled(false);
            btnNovo.setEnabled(!false);
            btnSalvar.setEnabled(!true);
            btnEditar.setEnabled(true);
            btnEcluir.setEnabled(true);
            btnListarCidade.setEnabled(false);
            cbxCidade.setEnabled(false);
            cbxEstado.setEnabled(false);
            txtPesquisa.setEnabled(true);
            btnPesquisar.setEnabled(true);

        } else {
            //String cpf = txtfCpf.getText().replaceAll("[.-]","");
            mod.setId(Integer.parseInt(txtCodigo.getText()));
            mod.setNome(txtNome.getText());
            mod.setEndereco(txtEndereco.getText());
            mod.setCpf(txtfCpf.getText().replaceAll("[.-]",""));
            mod.setRg(txtfRg.getText());
            mod.setBairro(txtBairro.getText());
            mod.setTelefone(txtfTelefone.getText());
            mod.setEstado((String) cbxEstado.getSelectedItem());
            mod.setCidade((String) cbxCidade.getSelectedItem());
            control.Altera(mod);
            txtEndereco.setEnabled(!true);
            txtNome.setEnabled(!true);
            txtfCpf.setEnabled(!true);
            txtfRg.setEnabled(!true);
            btnNovo.setEnabled(!false);
            btnSalvar.setEnabled(!true);
            btnEditar.setEnabled(true);
            btnEcluir.setEnabled(true);
            btnListarCidade.setEnabled(false);
            txtBairro.setEnabled(false);
            txtfTelefone.setEnabled(false);
            cbxCidade.setEnabled(false);
            cbxEstado.setEnabled(false);
            btnPesquisar.setEnabled(true);
            txtPesquisa.setEnabled(true);

        }
        flag = 1;

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        flag = 2;
        txtEndereco.setEnabled(true);
        txtNome.setEnabled(true);
        txtfCpf.setEnabled(true);
        txtfRg.setEnabled(true);
        txtBairro.setEnabled(true);
        txtfTelefone.setEnabled(true);
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(!true);
        btnEcluir.setEnabled(!true);
        cbxCidade.setEnabled(true);
        cbxEstado.setEnabled(true);
        btnListarCidade.setEnabled(true);
        txtPesquisa.setEnabled(false);
        btnPesquisar.setEnabled(false);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcluirActionPerformed
        mod.setId(Integer.parseInt(txtCodigo.getText()));
        mod.setNome(txtNome.getText());
        mod.setEndereco(txtEndereco.getText());
        mod.setCpf(txtfCpf.getText());
        mod.setRg(txtfRg.getText());
        mod.setBairro(txtBairro.getText());
        mod.setTelefone(txtfTelefone.getText());
        mod.setCidade((String) cbxCidade.getSelectedItem());
        mod.setEstado((String) cbxEstado.getSelectedItem());
        control.ExcluirCliente(mod);
        txtEndereco.setEnabled(!true);
        txtNome.setEnabled(!true);
        txtfCpf.setEnabled(!true);
        txtfRg.setEnabled(!true);
        btnNovo.setEnabled(!false);
        btnSalvar.setEnabled(!true);
        btnEditar.setEnabled(!true);
        btnEcluir.setEnabled(!true);
        txtCodigo.setText("");
        txtEndereco.setText("");
        txtNome.setText("");
        txtfCpf.setText("");
        txtfRg.setText("");
        txtBairro.setText("");
        txtfTelefone.setText("");
        cbxCidade.removeAllItems();
        cbxEstado.removeAllItems();

    }//GEN-LAST:event_btnEcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        preencherTabela();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        String descricaoCliente = "" + tblCliente.getValueAt(tblCliente.getSelectedRow(), 0);
        ConnCliente.conexao();
        connCidade.conexao();
        connEstado.conexao();
        try {

            ConnCliente.executaSQL("select * from clientes where nome_cliente ='" + descricaoCliente + "'");
            ConnCliente.rs.first();
            txtCodigo.setText(String.valueOf(ConnCliente.rs.getInt("id_cliente")));
            txtEndereco.setText(ConnCliente.rs.getString("endereco_cliente"));
            txtfCpf.setText(ConnCliente.rs.getString("cpf_cliente"));
            txtfRg.setText(ConnCliente.rs.getString("rg_cliente"));
            txtNome.setText(ConnCliente.rs.getString("nome_cliente"));
            txtBairro.setText(ConnCliente.rs.getString("bairro_cliente"));
            txtfTelefone.setText(ConnCliente.rs.getString("telefone_clientes"));
            connEstado.executaSQL("select * from estado where id_estado =" + ConnCliente.rs.getInt("id_estado"));
            connEstado.rs.first();
            cbxEstado.setSelectedItem(connEstado.rs.getString("sigla_estado"));
            connCidade.executaSQL("select nome_cidade from cidade where id_cidade =" + ConnCliente.rs.getInt("id_cidade"));
            connCidade.rs.first();
            cbxCidade.addItem(connCidade.rs.getString("nome_cidade"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não foi Possivel Carregar o Registro!!\n ERRO:  " + ex);
        }
        btnEcluir.setEnabled(true);
        btnEditar.setEnabled(true);
    }//GEN-LAST:event_tblClienteMouseClicked

    private void btnListarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCidadeActionPerformed
        CarregaCidade();
    }//GEN-LAST:event_btnListarCidadeActionPerformed

    public void preencherTabela() {
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Cliente", "Telefone", "Cidade"};
        ConnCliente.conexao();
        ConnCliente.executaSQL("select * from clientes inner join cidade on clientes.id_cidade=cidade.id_cidade where nome_cliente like '%" + txtPesquisa.getText() + "%' ");
        try {
            ConnCliente.rs.first();
            do {
                dados.add(new Object[]{ConnCliente.rs.getString("nome_cliente"), ConnCliente.rs.getString("telefone_clientes"), ConnCliente.rs.getString("nome_cidade")});
            } while (ConnCliente.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você Não Possui Clientes Cadastrados !!\n ERRO:  " + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tblCliente.setModel(modelo);
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(250);
        tblCliente.getColumnModel().getColumn(0).setResizable(false);
        tblCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblCliente.getColumnModel().getColumn(1).setResizable(false);
        tblCliente.getColumnModel().getColumn(2).setPreferredWidth(198);
        tblCliente.getColumnModel().getColumn(2).setResizable(false);
        tblCliente.getTableHeader().setResizingAllowed(false);
        tblCliente.setAutoResizeMode(tblCliente.AUTO_RESIZE_OFF);
        tblCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void CarregaEstado() {
        ConnCliente.conexao();
        cbxEstado.removeAllItems();

        try {
            ConnCliente.executaSQL("select * from estado order by sigla_estado");
            ConnCliente.rs.first();
            do {
                cbxEstado.addItem(ConnCliente.rs.getString("sigla_estado"));
            } while (ConnCliente.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não Foi Possivel Carregar os Estados!!");
        }

    }

    public void CarregaCidade() {
        ConnCliente.conexao();
        cbxCidade.removeAllItems();

        try {
            ConnCliente.executaSQL("select * from cidade inner join estado on cidade.id_estado=estado.id_estado where sigla_estado='" + cbxEstado.getSelectedItem() + "'");
            ConnCliente.rs.first();
            do {
                cbxCidade.addItem(ConnCliente.rs.getString("nome_cidade"));
            } while (ConnCliente.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não Tem Cidade Cadastrada Para Este Estado! Favor Cadastre Uma Cidade\n"
                    + " Para Continuar!!");

        }

    }

    public void limpaCampos() {
        txtBairro.setText("");
        txtfTelefone.setText("");
        txtCodigo.setText("");
        txtEndereco.setText("");
        txtNome.setText("");
        txtfRg.setText("");
        txtfCpf.setText("");
        cbxCidade.removeAllItems();
        cbxEstado.removeAllItems();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEcluir;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnListarCidade;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbxCidade;
    private javax.swing.JComboBox cbxEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JFormattedTextField txtfCpf;
    private javax.swing.JFormattedTextField txtfRg;
    private javax.swing.JFormattedTextField txtfTelefone;
    // End of variables declaration//GEN-END:variables
}
